// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vaccjauiwxjwequieppi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhY2NqYXVpd3hqd2VxdWllcHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDYzODYsImV4cCI6MjA3MjU4MjM4Nn0.9H153Rom2jFuCkuLtQJBihHiE7J9d3L0Fe4-LXGTbFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);