# De naam van de workflow
name: Deploy Frontend to VPS

# Trigger: deze workflow draait bij elke push naar de 'main' branch
on:
  push:
    branches:
      - main

# Taken die uitgevoerd moeten worden
jobs:
  deploy:
    # De virtuele machine waarop de actie draait
    runs-on: ubuntu-latest

    # De stappen van de taak
    steps:
      # Stap 1: Haal de code van de repository op
      - name: Checkout code
        uses: actions/checkout@v3

      # Stap 2: Installeer sshpass (nodig voor wachtwoord-authenticatie)
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # Stap 3: Voer de deployment-commando's uit op de VPS
      - name: Deploy Frontend to VPS
        run: |
          sshpass -p '${{ secrets.VPS_PASSWORD }}' ssh -o StrictHostKeyChecking-no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e

            cd /var/www/sm-movement/
            
            git pull
            
            # Gebruik pnpm, de package manager die dit project verwacht
            pnpm install
            
            pnpm run build
            
            # Herstart de app via het stabiele ecosystem.config.js bestand
            pm2 restart ecosystem.config.js
            
            echo "Frontend deployment is succesvol afgerond met pnpm."
          EOF