# De naam van de workflow
name: Deploy Frontend to VPS

# Trigger: deze workflow draait bij elke push naar de 'main' branch
on:
  push:
    branches:
      - main

# Taken die uitgevoerd moeten worden
jobs:
  deploy:
    # De virtuele machine waarop de actie draait
    runs-on: ubuntu-latest

    # De stappen van de taak
    steps:
      # Stap 1: Haal de code van de repository op
      - name: Checkout code
        uses: actions/checkout@v3

      # Stap 2: Installeer sshpass (nodig voor wachtwoord-authenticatie)
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # Stap 3: Voer de deployment-commando's uit op de VPS
      - name: Deploy Frontend to VPS
        run: |
          # Gebruik sshpass om het wachtwoord veilig door te geven via een secret.
          sshpass -p '${{ secrets.VPS_PASSWORD }}' ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            # Stop het script direct als een commando mislukt
            set -e

            # --- FRONT-END DEPLOYMENT ---
            echo "--- Starten met Frontend deployment ---"
            # Ga naar de frontend projectmap op de server
            cd /var/www/sm-movement/
            
            echo "--> Laatste code ophalen van GitHub..."
            git pull
            
            echo "--> Dependencies installeren met npm..."
            npm install
            
            echo "--> Frontend builden voor productie..."
            npm run build
            
            echo "--> Frontend applicatie herstarten met PM2..."
            pm2 restart sm-movement-frontend
            
            echo "Frontend deployment is succesvol afgerond."
          EOF